/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.github.deaktator.testing.p2;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Protocol2 {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Protocol2\",\"namespace\":\"testing.p2\",\"types\":[{\"type\":\"record\",\"name\":\"ScoreN\",\"fields\":[{\"name\":\"value\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"int\"}],\"default\":null}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends Protocol2 {
    public static final org.apache.avro.Protocol PROTOCOL = Protocol2.PROTOCOL;
  }
}